Starting embedded-redis fails
```
java.lang.IllegalStateException: Failed to load ApplicationContext
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'embeddedRedis' defined in class path resource [com/playtika/test/redis/EmbeddedRedisBootstrapConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.testcontainers.containers.GenericContainer]: Factory method 'redis' threw exception; nested exception is java.lang.IllegalArgumentException: Failed to load file - redis.conf.template
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.testcontainers.containers.GenericContainer]: Factory method 'redis' threw exception; nested exception is java.lang.IllegalArgumentException: Failed to load file - redis.conf.template
Caused by: java.lang.IllegalArgumentException: Failed to load file - redis.conf.template
Caused by: java.nio.file.FileSystemNotFoundException
```